name: GUIShop
main: com.pablo67340.guishop.Main
version: ${project.version}
author: pablo67340
description: Shop Plugin for any server.
depend: [Vault]
softdepend: [BetterReload]
api-version: 1.13
permissions:
    guishop.use:
        default: op
        description: Grants access to GUIShop
    guishop.shop.*:
        default: op
        description: Grants access to specific items in shop
    guishop.reload:
        default: op
        description: Grants access to reload shops
    guishop.creator:
        default: op
        description: Grants access to GUIShop Creator
commands:
  guishop:
    description: Base GUIShop command. Displays help.
    permission: guishop.use
    aliases: gs
  guishopuser:
    description: GUIShop alias for buy and sell commands.
    permission: guishop.use
  value:
    description: View an Item's Buy or Sell Value.
    permission: guishop.value
    aliases: [val, gvalue]