name: GUIShop
main: com.pablo67340.guishop.GUIShop
version: ${project.version}
author: pablo67340
description: Shop plugin for any server.
depend: [ Vault ]
softdepend: [ PlaceholderAPI ]
api-version: 1.13

permissions:
  guishop.use:
    default: op
    description: Grants access to GUIShop
  guishop.shop.*:
    default: op
    description: Grants access to specific items in shop
  guishop.reload:
    default: op
    description: Grants access to reload shops
  guishop.creator:
    default: op
    description: Grants access to the GUIShop creator

commands:
  guishop:
    description: Base GUIShop command. Displays help.
    permission: guishop.use
    aliases: gs
  guishopuser:
    description: GUIShop alias for buy and sell commands.
    permission: guishop.use